### ISSUE TITLE
After the setup is finished, accesspwn does not appear

### ISSUE THREAD

**Issue by Dadoudu64** [msfcode/accespwn#2]
After I finished the setup, it tells me that I have to do ./accespwn to launch except that there is no accespwn file on my pc

Thanks for your reply.

**Comment by msfcode** [comment]
### Hello @Dadoudu64  Do not worry That because i close the tool for some updates any way yoy can retry using it 
this time please read the new installation method if you get any errors please contact me instagram.com/msfcode

Also i the project not finished yet ..  but you can use it ,,.
Their is a new and powerfull update for the backdoor : i will add screenshoting, upload malicious file, copy or cut files from victim pc ... 
The keylogger option not finished yet... It will be powerfull but you have to wait 

I will add The Web App Vulnerability scanner to discover xss and sql injections ..

Just wait for Accespwn V3.0 it will be complet and powerfull 
maybe you will find some exploits for android ...

**Comment by Dadoudu64** [comment]
Okey thanks
